# Generated by Django 3.0.6 on 2025-02-25 09:26

from django.db import migrations, models



class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='profile_pic',
            field=models.ImageField(upload_to='staff_pics/', null=True, blank=True),
        ),
    ]
