# Generated by Django 3.0.6 on 2025-02-26 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0003_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Timetable',
        ),
    ]
