# Generated by Django 3.0.6 on 2025-02-26 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_management_app', '0005_notice'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notice',
            new_name='StaffNotice',
        ),
    ]
